@startuml Product
!startsub Product

class Product {
    -id string
    -title string
    -description string
    -stock int
    -price double
    -image string
    +User(string id, string title, String description, int stock, double price, string image)
}

!endsub
@enduml

